// This file is autogenerated. Changes will be overwritten.
#include <7HEHEGDA3T/moc_CustomScrollBinder.cpp>
#include <7HEHEGDA3T/moc_DragHelper.cpp>
#include <7HEHEGDA3T/moc_WakeWordDetector.cpp>
#include <FGANCVEOR2/moc_dialog.cpp>
#include <XS2PMGX5K5/moc_history.cpp>
#include <XS2PMGX5K5/moc_historychild.cpp>
#include <WXIUEZC6O5/moc_settingchild_about.cpp>
#include <WXIUEZC6O5/moc_settingchild_appLauncher.cpp>
#include <WXIUEZC6O5/moc_settingchild_char.cpp>
#include <WXIUEZC6O5/moc_settingchild_general.cpp>
#include <WXIUEZC6O5/moc_settingchild_llm.cpp>
#include <WXIUEZC6O5/moc_settingchild_plugin.cpp>
#include <WXIUEZC6O5/moc_settingchild_screenCapture.cpp>
#include <WXIUEZC6O5/moc_settingchild_speech.cpp>
#include <WXIUEZC6O5/moc_settingchild_vits.cpp>
#include <ETVDF2CPEP/moc_setting.cpp>
#include <GAHAFR22D5/moc_tachie.cpp>
